feat: add checking of user existence in DB in auth Middleware and fetchMe Rest Api for User (#40012)
permil-successive/javascript-server pull request #14
Opened 2020-02-07 10:22 UTC by permil-successive

@Prabal555 @nxvinay

2020-02-07 10:23 UTC, permil-successive commented
token

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZW1haWwiOiJ2aW5heUBzdWNjZXNzaXZlLnRlY2giLCJpc3MiOiJTdWNjZXNzaXZlIFRlY2hub2xvZ2llcyIsImlkIjoiNWUzZDFlNmNjYmVhYmU2NmMxNmQyNzBiIiwiaWF0IjoxNTE2MjM5MDIyfQ.SIe_hxuvNjoH5PA7ZDv10C_vsHcVm5JSr9PCfLCbGpU

2020-02-07 10:25 UTC, permil-successive commented
db document

{
    "_id" : "5e3d1e6ccbeabe66c16d270b",
    "hobbies" : [ 
        "Traveling"
    ],
    "name" : "Naveen",
    "role" : "head-trainer",
    "address" : "Pune",
    "dob" : ISODate("1992-12-31T18:30:00.000Z"),
    "email" : "vinay@successive.tech",
    "mobileNumber" : 1231231230,
    "__v" : 0
}

2020-02-11 11:27 UTC, Prabal555 commented
Please take care of the following issues: 

1. there should be some unique key in your create object.

2020-02-11 11:28 UTC, Prabal555 requested changes

2020-02-11 11:28 UTC, Prabal555 commented on src/controllers/trainee/routes.ts
are two delete method intentional

2020-02-11 11:28 UTC, Prabal555 commented on src/controllers/trainee/validations.ts
> +      errorMessage: 'imit is invalid',
typo

2020-02-11 11:28 UTC, Prabal555 commented on src/controllers/user/routes.ts
> +const moduleName = 'user';
the module name will not work, use 'users' instead

2020-02-11 11:28 UTC, Prabal555 commented on src/controllers/trainee/validations.ts
> +      errorMessage: 'Name is required',
validations don not cover the entire JSON object that is used for creation

2020-02-11 11:29 UTC, Prabal555 requested changes

2020-02-11 11:29 UTC, Prabal555 commented on src/controllers/trainee/validations.ts
> +      errorMessage: 'imit is invalid',
limit and skip does not work on the api

2020-02-11 12:12 UTC, Prabal555 commented
Please add a check in the for ids not available for update and delete.

2020-02-11 12:23 UTC, permil-successive commented on src/controllers/trainee/routes.ts
deleted unwanted method

2020-02-13 15:56 UTC, merged