feat: add versionable repository (#40013)
permil-successive/javascript-server pull request #15
Opened 2020-02-12 12:59 UTC by permil-successive

@nxvinay  @Prabal555 

https://redmine.successive.tech/issues/40013

2020-02-13 15:58 UTC, Prabal555 commented on src/controllers/user/controller.ts
> +      const data = await this.userRepository.create(req.body, req.user.originalId);
destructure

2020-02-13 16:26 UTC, Prabal555 requested changes

2020-02-13 16:26 UTC, Prabal555 commented on src/controllers/user/controller.ts
> +      const data = await this.userRepository.list(req.query.skip, req.query.limit);
destructure missing

2020-02-13 16:26 UTC, Prabal555 commented on src/controllers/user/controller.ts
> +      const data = await this.userRepository.update(req.body.id, req.body.dataToUpdate, req.user.originalId);
destructure missing

2020-02-13 16:26 UTC, Prabal555 commented on src/controllers/user/controller.ts
> +      const data = await this.userRepository.delete(req.params.id, req.user.originalId);
destructure missing

2020-02-13 16:26 UTC, Prabal555 commented on src/libs/routes/authMiddleware.ts
> +    req.user = user; // assigning user to request for further use
better shifting to locals

2020-02-13 16:26 UTC, Prabal555 commented on src/repositories/versionable/VersionableRepository.ts
> +  private _deleteQuery = { deletedAt: {'$exists': false} };
why is _ prefixed with variable here

2020-02-13 16:26 UTC, Prabal555 commented on src/repositories/versionable/VersionableRepository.ts
> +  private generateBy(currentUser: string) {
Generic method variable should not be named like 'user'

2020-02-13 16:26 UTC, Prabal555 commented on src/repositories/versionable/VersionableRepository.ts
> +  async create(data, currentUser: string): Promise<D> {
variable name should be as user

2020-02-14 06:53 UTC, permil-successive commented on src/repositories/versionable/VersionableRepository.ts
> +  private _deleteQuery = { deletedAt: {'$exists': false} };
I am used _ for showing constants. Now dropped.

2020-02-14 07:37 UTC, permil-successive commented on src/repositories/versionable/VersionableRepository.ts
> +  private generateBy(currentUser: string) {
this **currentUser** variable is used for that user who is performing operation on record. It is common for every record.

2020-02-17 11:37 UTC, Prabal555 commented
Http Status code and request returns different code
![image](https://user-images.githubusercontent.com/45360184/74649531-c7b1e680-51a5-11ea-9018-9ffbe31bf5de.png)

Email is not validated properly in the data to update, Mobile number is not validated properly in the data to update and the dob is returning two errors in the same message.
![image](https://user-images.githubusercontent.com/45360184/74649914-8f5ed800-51a6-11ea-8d85-56937f5e00e6.png)

Error message is not correct for invalid hobbies type
![image](https://user-images.githubusercontent.com/45360184/74649885-8110bc00-51a6-11ea-90a1-4ec7fe38938f.png)

An incorrect response is returned from the service, try to **never return internal server error from the server** please make sure to check the validity of thing first like date in this case
![image](https://user-images.githubusercontent.com/45360184/74650065-e06ecc00-51a6-11ea-8623-5047bba880b8.png)

2020-02-17 11:47 UTC, Prabal555 requested changes

2020-02-17 11:47 UTC, Prabal555 commented on src/repositories/versionable/VersionableRepository.ts
> +    this.isOperationSuccess(updatedPreviousData);
what kind of variable name is updatedPreviousData

2020-02-17 11:47 UTC, Prabal555 commented on src/repositories/versionable/VersionableRepository.ts
> +      createdBy: this.generateCreatedInfo(currentUser).createdBy,
these methods could have been generally called getCreatedInfo instead of generatetCreatedInfo

2020-02-17 11:48 UTC, Prabal555 commented
Please make sure that created and updated at dates are same:

![image](https://user-images.githubusercontent.com/45360184/74650868-a1417a80-51a8-11ea-801f-17683efbc70b.png)

2020-02-17 12:48 UTC, permil-successive commented
> Please make sure that created and updated at dates are same:
> 
> ![image](https://user-images.githubusercontent.com/45360184/74650868-a1417a80-51a8-11ea-801f-17683efbc70b.png)

done

2020-02-17 12:59 UTC, permil-successive commented on src/repositories/versionable/VersionableRepository.ts
> +    this.isOperationSuccess(updatedPreviousData);
Sir,

actually this variable stores the result of update query on original document for updating deleteAt. May you help me suggesting better name.

2020-02-18 09:55 UTC, permil-successive commented
> Http Status code and request returns different code
> ![image](https://user-images.githubusercontent.com/45360184/74649531-c7b1e680-51a5-11ea-9018-9ffbe31bf5de.png)
> 
> Email is not validated properly in the data to update, Mobile number is not validated properly in the data to update and the dob is returning two errors in the same message.
> ![image](https://user-images.githubusercontent.com/45360184/74649914-8f5ed800-51a6-11ea-8d85-56937f5e00e6.png)
> 
> Error message is not correct for invalid hobbies type
> ![image](https://user-images.githubusercontent.com/45360184/74649885-8110bc00-51a6-11ea-90a1-4ec7fe38938f.png)
> 
> An incorrect response is returned from the service, try to **never return internal server error from the server** please make sure to check the validity of thing first like date in this case
> ![image](https://user-images.githubusercontent.com/45360184/74650065-e06ecc00-51a6-11ea-8623-5047bba880b8.png)

resolved

2020-02-19 09:57 UTC, merged